/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ClientJNI */

#ifndef _Included_ClientJNI
#define _Included_ClientJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ClientJNI
 * Method:    Start
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ClientJNI_Start
  (JNIEnv *, jobject);

/*
 * Class:     ClientJNI
 * Method:    Stop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ClientJNI_Stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
